# Generated by Django 3.0.6 on 2020-05-26 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('debut_date', models.DateField()),
                ('member', models.TextField()),
                ('description', models.TextField()),
                ('interest', models.PositiveIntegerField(default=0)),
                ('profile_image', models.ImageField(blank=True, null=True, upload_to='indiecator/')),
            ],
        ),
    ]
