# Generated by Django 3.0.6 on 2020-05-24 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indiecator_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artist',
            name='debut_date',
            field=models.DateField(),
        ),
    ]
